name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  core-checks:
    name: Core + WASM (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Test core
        run: cargo test --workspace --all-features
      - name: Build WASM
        run: cargo build -p obrero-wasm --target wasm32-unknown-unknown

  firmware-checks:
    name: Firmware (xtensa)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware
    strategy:
      fail-fast: false
      matrix:
        action:
          - command: build
            args: --release
          - command: fmt
            args: --all -- --check --color always
          - command: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: firmware
      - name: Run command
        run: cargo ${{ matrix.action.command }} ${{ matrix.action.args }}
